### ISSUE TITLE
有没有不用ctex套装的

### ISSUE THREAD

**Issue by chenyu-01** [MrDongdongLin/xtuthesis#1]
![image](https://user-images.githubusercontent.com/63953834/102014038-f29da480-3d8e-11eb-8f68-b2a3bdfbe660.png)
ctex已经放弃更新了。

**Comment by MrDongdongLin** [comment]
可以用book+CJK制作一个模板，比这个麻烦得多。虽然CTEX不更新了，但是CTEX的包对中文的支持比较友好，功能比较齐全。

**Comment by MrDongdongLin** [comment]
> ![image](https://user-images.githubusercontent.com/63953834/102014038-f29da480-3d8e-11eb-8f68-b2a3bdfbe660.png)
> ctex已经放弃更新了。

可以用book+CJK制作一个模板，比这个麻烦得多。虽然CTEX不更新了，但是CTEX的包对中文的支持比较友好，功能比较齐全。
